#!/bin/bash

function install_snapshot_scheduler {
    echo_summary "Installing Snapshot Scheduler plugin"
    sudo apt-get update
    sudo apt-get install -y python3-venv
    python3 -m venv /opt/stack/snapshot-scheduler/app/venv
    source /opt/stack/snapshot-scheduler/app/venv/bin/activate
    pip install -r /opt/stack/snapshot-scheduler/app/requirements.txt
}

function configure_snapshot_scheduler {
    echo_summary "Configuring Snapshot Scheduler plugin"
    sudo cp /opt/stack/snapshot-scheduler/snap-scheduler.service /etc/systemd/system/
    sudo systemctl daemon-reexec
    sudo systemctl enable snap-scheduler.service
}

function start_snapshot_scheduler {
    echo_summary "Starting Snapshot Scheduler plugin"
    sudo systemctl start snap-scheduler.service
}
