clouds:
  devstack:
    auth:
      auth_url: http://127.0.0.1:5000
      username: demo
      password: secret
      project_name: demo
      user_domain_name: Default
      project_domain_name: Default
    region_name: RegionOne
    interface: public
    identity_api_version: 3
