clouds:
  cloudwatcher-devstack:
    auth:
      auth_url: http://10.0.2.15/identity
      username: admin
      password: secret
      project_name: admin
      user_domain_name: Default
      project_domain_name: Default
    region_name: RegionOne
    interface: public
    identity_api_version: 3
